### ISSUE TITLE
Toasts reappearing after being dismissed

### ISSUE THREAD

**Issue by Nattfisk** [KDE/snoretoast#6]
I am using this tool in a .bat script with these commands:
snoretoast -t "%Title%" -m "added to library" -p "image.png" -id %Title%

it shows upp nicely, but when i dismiss it in the action center it reappears after a couple of seconds (no toast, just the entry in action center).

what am i missing? Running Windows 10

**Comment by TheOneRing** [comment]
Moved to KDE Phabricator https://phabricator.kde.org/T850
